# permissions for end users to edit accounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: upcloud-api-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: account-editor-role
rules:
- apiGroups:
  - upcloud.visdmin.com
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - upcloud.visdmin.com
  resources:
  - accounts/status
  verbs:
  - get
