# permissions for end users to view simpleplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: upcloud-api-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: simpleplan-viewer-role
rules:
- apiGroups:
  - upcloud.visdmin.com
  resources:
  - simpleplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - upcloud.visdmin.com
  resources:
  - simpleplans/status
  verbs:
  - get
