apiVersion: upcloud.visdmin.com/v1alpha1
kind: Account
metadata:
  labels:
    app.kubernetes.io/name: upcloud-api-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: account-sample
spec:
  # TODO(user): Add fields here
